version: 2

jobs:
  "python-2.7": &test-template
    docker:
      - image: circleci/python:2.7-stretch-browsers
        environment:
          REQUIREMENTS_FILE: dev-requirements.txt
          PYLINTRC: .pylintrc
          TOX: py27,py27-dj{109,110,111}
          TOX_PYTHON_27: python

    steps:
      - checkout

      - run:
          name: Write deps cache key
          command: cat "$REQUIREMENTS_FILE" > reqs.txt

      - run:
          name: Write job name
          command: echo $CIRCLE_JOB > circlejob.txt

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "tox.ini" }}-{{ checksum "reqs.txt" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "circlejob.txt" }}

      - run:
          name: Install dependencies
          command: |
              sudo pip install --upgrade virtualenv
              python -m venv venv || virtualenv venv
              . venv/bin/activate
              pip install tox

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "tox.ini" }}-{{ checksum "reqs.txt" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "circlejob.txt" }}
          paths:
              - "venv"
              - ".tox"

      - run:
          name: Run tox
          command: |
              . venv/bin/activate
              tox tox.ini -e $TOX

  "python-3.6":
    <<: *test-template
    docker:
      - image: circleci/python:3.6-stretch-browsers
        environment:
          REQUIREMENTS_FILE: dev-requirements.txt
          PYLINTRC: .pylintrc
          TOX: py36,py36-dj{109,110,111,200,201}
          TOX_PYTHON_36: python

  "python-3.7":
    <<: *test-template
    docker:
    - image: circleci/python:3.7-stretch-browsers
      environment:
        REQUIREMENTS_FILE: dev-requirements.txt
        PYLINTRC37: .pylintrc37
        TOX: py37,py37-dj{109,110,111,200,201}
        TOX_PYTHON_37: python

workflows:
  version: 2
  build:
    jobs:
      - "python-2.7"
      - "python-3.6"
      - "python-3.7"
